config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'users#index'


  get "review", to: "users#review"
  get "newtemplate", to: "users#newtemplate"

  resources :resumes
  resources :introductions
  resources :objectives
  resources :summary
  resources :skills
  resources :experiences
  resources :projects
  resources :otherprojects
  resources :educations
  resources :reskills
  resources :sections do
    resources :subsections, only: [:new, :create]
  end
  resources :subsections, only:[:index, :edit, :update, :destroy]
  resources :users
end

app/models/education.rb
class Education < ApplicationRecord
	belongs_to :resume
end

app/models/experience.rb
class Experience < ApplicationRecord
	belongs_to :resume
	has_many :projects
end

app/models/introduction.rb
class Introduction < ApplicationRecord
	belongs_to :resume
end

app/models/objective.rb
class Objective < ApplicationRecord

	belongs_to :resume
end

app/models/otherproject.rb
class Otherproject < ApplicationRecord
	belongs_to :resume
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :experiences
	belongs_to :resume
end

app/models/reskill.rb
class Reskill < ApplicationRecord
	belongs_to :resume
	belongs_to :skill
end

app/models/resume.rb
class Resume < ApplicationRecord
	has_one :introduction
	has_one :summary
	has_one :objective
	has_many :reskills
	has_many :skills, :through => :reskills
	has_many :projects
	has_many :otherprojects
	has_many :educations
	has_many :experiences
	has_many :sections
	has_many :subsections, :through => :sections
	belongs_to :user
end

app/models/section.rb
class Section < ApplicationRecord
	has_many :subsections
	belongs_to :resume
end

app/models/skill.rb
class Skill < ApplicationRecord
	has_many :reskills
	has_many :resume, :through => :reskills
end

app/models/subsection.rb
class Subsection < ApplicationRecord
	belongs_to :section
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :resume
end

app/controllers/objectives_controller.rb
class ObjectivesController < ApplicationController
	
	def index
		@objective = User.find(current_user.id).resume.objective
	end

	def show
		@objective = User.find(current_user.id).resume.objective
	end

	def new
		@user_resume = User.find(current_user.id).resume.id
		@objective = Objective.new(params[:resume_id])
	end

	def create
		@objective = Objective.create(resume_id: params[:objective][:resume_id],description: params[:objective][:description])
		if @objective.save
			redirect_to users_path
			flash[:notice] = "Job Created"
		else
			render 'objective/new'
		end
	end
	
	def edit
		@objective = User.find(current_user.id).resume.objective
	end

	def update
		@objective = User.find(current_user.id).resume.objective
		@objective.update_attributes(objective_params)
		redirect_to users_path
	end

	def destroy
		@objective = User.find(current_user.id).resume.objective
		@objective.destroy
		redirect_to users_path
	end

	private

  	def set_resume
    	@resume = Resume.find_by(user: params[:resume_id])
  	end

  	def set_objective
    	@objective = Objective.find_by(resume: params[:id])
  	end

  	def objective_params 
  		params.require(:objective).permit(:description)
  	end

end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/objectives_helper.rb
module ObjectivesHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/reskills_helper.rb
module ReskillsHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/objectives/edit.html.erb
<div class= "uk-container uk-background-muted uk-padding uk-panel" style="padding: 50px;margin-top: 150px;">
    <h2> Add your Objective here </h2><br>
        <%= form_for @objective do |f| %>

            <%= f.hidden_field :resume_id, :value => @user_resume %>
             
        
            <label class="uk-form-label" for="form-stacked-text">
                Objective
            </label>
            <div class="uk-form-controls ">
               <input class = "uk-input" =  <%= f.text_field :description, :required => true %>
            </div>
            <br>
           <button class="uk-button uk-button-primary"
                 <%= submit_tag "Add" %> UPDATE
        <% end %>
        
</div>

app/views/objectives/index.html.erb
 <% @objective.each do |t| %>
    <%= render partial: "shared/objective", :collection => @objective %>
    <div class = "uk-container-small uk-align-center">
        <a <%= link_to "Edit", edit_objective_path(t) %></a>|
        <a  <%= link_to "Remove", objective_path(t), method: :delete, data: { confirm: "Are you sure?" } %></a>|
        <a <%= link_to "Next", new_skill_path(t) %></a>
    </div>
<% end %>

app/views/objectives/new.html.erb
<div class= "uk-container uk-background-muted uk-padding uk-panel" style="padding: 50px;margin-top: 150px;">
    <h2> Add your Objective here </h2><br>
        <%= form_for @objective do |f| %>

            <%= f.hidden_field :resume_id, :value => @user_resume %>
             
             Objective
            <div>
                <textarea class="uk-textarea" rows="5" placeholder="Describe your job"
                    <%= f.text_field :description, :required => true %>
                </textarea>
            </div>
            <br>
            <button class="uk-button uk-button-primary"
                 <%= submit_tag "Add" %> ADD
             </button>
    
        <% end %>
        
</div>