config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'users#index'


  get "review", to: "users#review"
  get "newtemplate", to: "users#newtemplate"

  resources :resumes
  resources :introductions
  resources :objectives
  resources :summary
  resources :skills
  resources :experiences
  resources :projects
  resources :otherprojects
  resources :educations
  resources :reskills
  resources :sections do
    resources :subsections, only: [:new, :create]
  end
  resources :subsections, only:[:index, :edit, :update, :destroy]
  resources :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :resume
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/plataformatec/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  #   @resume = Resume.new(resume_parse.merge(user_id: session[:user_id], user_id: user_id))
 
  # end

  # POST /resource
  def create
    super
    Resume.create(user_id: current_user.id)  
  end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @user_resume_introductions = current_user.resume.introduction
    @user_resume_objective = current_user.resume.objective
    @user_resume_experiences = current_user.resume.experiences
    @user_resume_otherprojects = current_user.resume.otherprojects
    @user_resume_education = current_user.resume.educations
    @user_resume_reskills = current_user.resume.reskills
    @user_resume_sections = current_user.resume.sections
    @user_resume_subsections = current_user.resume.subsections

     respond_to do |format|
      format.html
      format.pdf do 
        # render pdf: 'resume',
        #      template: 'users/show.html.erb',
        #      locals: {:intro => @user_resume_introductions}
        pdf = render_to_string pdf: 'resume',
                              template: 'users/show.html.erb',
                              encoding: 'utf-8'
        send_data(pdf, filename: 'resume.pdf', type: 'application/pdf', desposition: 'attachment')
      end
    end
  end


  def newtemplate
    @resume = current_user.resume
     @user_resume_sections = current_user.resume.sections
    @user_resume_subsections = current_user.resume.subsections
    # @user_resume_introduction = current_user.resume.introduction
    # @user_resume_objective = current_user.resume.objective
    # @user_resume_experiences = current_user.resume.experiences
    # @user_resume_otherprojects = current_user.resume.otherprojects
    # @user_resume_education = current_user.resume.educations
    # @user_resume_reskills = current_user.resume.reskills
    respond_to do |format|
      format.html
      format.pdf do 
        # render pdf: 'resume',
        #      template: 'users/show.html.erb',
        #      locals: {:intro => @user_resume_introductions}
        pdf = render_to_string pdf: 'resume',
                              template: 'users/newtemplate.html.erb',
                              encoding: 'utf-8'
        send_data(pdf, filename: 'resume.pdf', type: 'application/pdf', desposition: 'attachment')
      end
    end
  end
  

	def new
    	@user = User.new
    	@resume = Resume.new
  end

  def show
    @user_resume_introductions = current_user.resume.introduction
    @user_resume_objective = current_user.resume.objective
    @user_resume_reskills = current_user.resume.reskills
    @user_resume_experiences = current_user.resume.experiences
    @user_resume_otherprojects = current_user.resume.otherprojects
    @user_resume_education = current_user.resume.educations
    @user_resume_sections = current_user.resume.sections
    @user_resume_subsections = current_user.resume.subsections
  end

  def edit
    @user_resume_introductions = current_user.resume.introduction
    @user_resume_objective = current_user.resume.objective
    @user_resume_reskills = current_user.resume.reskills
    @user_resume_experiences = current_user.resume.experiences
    @user_resume_otherprojects = current_user.resume.otherprojects
    @user_resume_education = current_user.resume.educations
    @user_resume_sections = current_user.resume.sections
    @user_resume_subsections = current_user.resume.subsections
  end

  def create
	    @resume = Resume.new
  end

  def review

  end

  	private
  		def set_user
    		@user = User.find_by(user: params[:id])
  		end

  		def set_resume
    		@resume = Resume.find_by(user_id: session[:user_id])
  		end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
	<div class="uk-container uk-animation-slide-left">
		<div class="uk-child-width-1-3@m uk-grid-small uk-grid-match" uk-grid>
			<div>
		        <div class="uk-card uk-card-default uk-card-body">
		            <h3 class="uk-card-title"><strong style="color: #f0506e;">B</strong>ASIC 	<strong style="color: #f0506e;">I</strong>NFO</h3>
		            <p>
				         <% if @user_resume_introductions == nil %>
						 	<h3 class="uk-animation-toggle"> 
						 		<a class="uk-button uk-button-primary uk-animation-shake" <%= link_to 'START', new_introduction_path %> </a>
						 	</h3>

						 	<% else %>
						 	
						 	<span uk-icon="file-edit">
						 	 	<a <%= link_to "Edit", edit_introduction_path(:id => @current_user.id) %></a> 
						 	</span> 
						 	<span uk-icon="trash">
						 		<a  <%= link_to "Remove", introduction_path(:id => @current_user.id), method: :delete, data: { confirm: "Are you sure?" } %></a>
						 	</span>
						 	<span  uk-icon="icon: check; ratio: 3.5" style="color: MediumSeaGreen;"></span>
						 <% end %>
		            </p>
		        </div>
		    </div>

		    <div>
		        <div class="uk-card uk-card-default uk-card-body">
		            <h3 class="uk-card-title"><strong style="color: #f0506e;">S</strong>UMMARY</h3>
		            <p>
				         <% if @user_resume_objective == nil %>
						 	<h3 class="uk-animation-toggle"> 
						 		<a class="uk-button uk-button-primary uk-animation-shake" <%= link_to 'START', new_objective_path %> </a>
						 	</h3>
						 	<% else %>
						 	<span uk-icon="file-edit">
						 	 	<a <%= link_to "Edit", edit_objective_path(:id => @current_user.id) %></a> 
						 	</span> 
						 	<span uk-icon="trash">
						 		<a  <%= link_to "Remove", objective_path(:id => @current_user.id), method: :delete, data: { confirm: "Are you sure?" } %></a>
						 	</span>
						 	<span  uk-icon="icon: check; ratio: 3.5" style="color: MediumSeaGreen;"></span>
						 <% end %>
		            </p>
		        </div>
		    </div>


		     <div>
		        <div class="uk-card uk-card-default uk-card-body">
		            <h3 class="uk-card-title"><strong style="color: #f0506e;">S</strong>KILLS</h3>
		      		<p>
						<% if @user_resume_reskills.length == 0 %>
					 		<h3 class="uk-animation-toggle"> 
						 		<a class="uk-button uk-button-primary uk-animation-shake" <%= link_to 'START', new_reskill_path %> </a>
					 		</h3>
					 	<% else %>
					 		 <a <%= link_to 'Add more', new_reskill_path %> </a> |
							 <span uk-icon="file-edit">
							 	<a <%= link_to "Edit", reskills_path(:id => @current_user.id) %></a> 
					 	 	 </span>
					 	 	 <span  uk-icon="icon: check; ratio: 3.5" style="color: MediumSeaGreen;"></span>
					 	<% end %>
				    </p>
		        </div>
		    </div>

		   <div>
		        <div class="uk-card uk-card-default uk-card-body">
		            <h3 class="uk-card-title"><strong style="color: #f0506e;">E</strong>XPERIENCES</h3>
		      		<p>
						<% if @user_resume_experiences.length == 0 %>
					 		<h3 class="uk-animation-toggle"> 
						 		<a class="uk-button uk-button-primary uk-animation-shake"<%= link_to 'START', new_experience_path %> </a>
					 		</h3>
					 	<% else %>
					 		 <a <%= link_to 'Add more', new_experience_path %> </a> |
							 <span uk-icon="file-edit">
							 	<a <%= link_to "Edit", experiences_path(:id => @current_user.id) %></a> 
					 	 	 </span>
					 	 	 <span  uk-icon="icon: check; ratio: 3.5" style="color: MediumSeaGreen;"></span>
					 	<% end %>
				    </p>
		        </div>
		    </div>

		   <div>
		        <div class="uk-card uk-card-default uk-card-body">
		            <h3 class="uk-card-title"><strong style="color: #f0506e;">P</strong>ROJECTS</h3>
		      		<p>
						<% if @user_resume_otherprojects.length == 0 %>
					 		<h3 class="uk-animation-toggle"> 
						 		<a class="uk-button uk-button-primary uk-animation-shake" <%= link_to 'START', new_otherproject_path %> </a>
					 		</h3>
					 	<% else %>
					 		 <a <%= link_to 'Add more', new_otherproject_path %> </a> |
					 		 <span uk-icon="file-edit">
							 	<a <%= link_to "Edit", otherprojects_path(:id => @current_user.id) %></a> 
					 	 	 </span>
					 	 	 <span  uk-icon="icon: check; ratio: 3.5" style="color: MediumSeaGreen;"></span>
					 	<% end %>
				    </p>
		        </div>
		    </div>
			
			<div>
		        <div class="uk-card uk-card-default uk-card-body">
		            <h3 class="uk-card-title"><strong style="color: #f0506e;">E</strong>DUCATIONS</h3>
		      		<p>
						<% if @user_resume_education.length == 0 %>
					 		<h3 class="uk-animation-toggle"> 
						 		<a class="uk-button uk-button-primary uk-animation-shake" <%= link_to 'START', new_education_path %> </a>
					 		</h3>
					 	<% else %>
					 		 <a <%= link_to 'Add more', new_education_path %> </a> |
							 <span uk-icon="file-edit">
							 	<a <%= link_to "Edit", educations_path(:id => @current_user.id) %></a> 
					 	 	 </span>
					 	 	 <span  uk-icon="icon: check; ratio: 3.5" style="color: MediumSeaGreen;"></span>
					 	<% end %>
				    </p>
		        </div>
		    </div>

		    <% if @user_resume_sections.length >= 1 %>
		    	<% @user_resume_sections.each do |t| %>
		     		<div>
			        	<div class="uk-card uk-card-default uk-card-body">
			        	
				            <h3 class="uk-card-title uk-text-uppercase"><%= t.name %></h3>
				      		<p>
								<% if t.subsections.length == 0 %>
							 		<h3 class="uk-animation-toggle"> 
								 		<a class="uk-button uk-button-primary uk-animation-shake"<%= link_to 'START', new_section_subsection_path(t) %> </a>
								 		 <a class="uk-button uk-button-primary uk-animation-shake" <%= link_to "Remove", section_path(t), method: :delete, data: { confirm: "Are you sure?" } %></a>
							 		</h3>
							 	<% else %>
							 		 <a <%= link_to 'Add more', new_section_subsection_path(t) %> </a> |
									 <span uk-icon="file-edit">
									 	<a <%= link_to "Edit", subsections_path(:id => @current_user.id) %></a> 
							 	 	 </span>
							 	 	 <span  uk-icon="icon: check; ratio: 3.5" style="color: MediumSeaGreen;"></span>
							 	<% end %>
						    </p>
			        	</div>
			        </div>
			    <% end %>
		    <% end %>
		</div>
	</div><br>
<br>

<a class="uk-button uk-button-primary myButton uk-padding uk-padding-remove-top uk-padding-remove-bottom" <%= link_to 'Add Section', new_section_path(:id => @current_user.id) %> </a>

<br><br> 

<!-- <div class="uk-child-width-1-2@m uk-grid-small uk-grid-match" uk-grid style="line-height: 1;"> -->
	<% if @user_resume_introductions && @user_resume_objective != nil %>
		<div class="uk-animation-toggle">
			<a class="uk-button uk-button-primary myButton uk-padding uk-padding-remove-top uk-padding-remove-bottom" <%= link_to 'Preview Template 1', user_path(:id => @current_user.id) %> </a>
			<a class="uk-button uk-button-primary myButton uk-padding uk-padding-remove-top uk-padding-remove-bottom " <%= link_to 'Preview Template 2', newtemplate_path(:id => @current_user.id) %> </a>
		</div><br>
		<% else %>
		<strong style="color: #1e87f0;">Note</strong> :- Fill out <strong style="color: #f0506e;">B</strong>asic<strong style="color: #f0506e;">I</strong>nfo and <strong style="color: #f0506e;">S</strong>ummary section to <strong style="color: #f0506e;">V</strong>iew your <strong style="color: #f0506e;">R</strong>esume.<br>
	<% end %>
	<% if @user_resume_introductions && @user_resume_objective && @user_resume_reskills.length && @user_resume_experiences.length && @user_resume_otherprojects.length && @user_resume_education.length != 0 %>
		
		<div class="uk-animation-toggle">
 			<a class="uk-button uk-button-primary myButton" <%= link_to "Download Template 1", users_path(:id => @current_user.id, format: 'pdf') %></a>
 			<a class="uk-button uk-button-primary myButton" <%= link_to "Download Template 2", newtemplate_path(:id => @current_user.id, format: 'pdf') %></a>
		</div>
		<% else %>
		<strong style="color: #1e87f0;">Note</strong> :- Fill out <strong style="color: #f0506e;">All</strong> the sections for <strong style="color: #f0506e;">D</strong>ownload your <strong style="color: #f0506e;">R</strong>esume.
	<% end %>



<br>
<hr class="uk-divider-icon">
<div class="uk-container">
	<h4 class="uk-text-center">
		<strong style="color: #f0506e;">R</strong>ecent <strong style="color: #f0506e;">R</strong>eview
	</h4><br>
</div>
<div class="uk-container uk-background-muted uk-padding uk-panel">
	<div class="uk-text-center" uk-grid>
    
	    <div class="uk-width-expand ">
	        <div class="uk-card  uk-card-body uk-background-muted">
	        	I found an article about how to write a professional resume on Resume Genius. Then I discovered the application. It's useful and simple to use, plus It's a free resume builder, Go for it.
	        </div>
	        <a style="color: #f0506e;" <%= link_to 'Send Review', review_path %> </a>

	    </div>
	    <div class="uk-width-auto">
	    	<span uk-icon="quote-right"></span>
	        <div class="uk-card  uk-card-body uk-background-muted"><strong style="color: #f0506e;">D</strong>avid <strong style="color: #f0506e;" >P</strong>atlut!</div>
	    </div>
	</div>
</div>
<br><br><br>

<nav class="uk-navbar" uk-navbar>

    <div class="uk-navbar-left ">
        <ul class="uk-navbar-nav uk-text-capitalize">
             <li>
                 <div>
                      Designed & Developed by
                      <div class="uk-navbar-subtitle uk-text-center"><strong style="color: #f0506e;" >Z</strong>akwan <strong style="color: #f0506e;">B</strong>haiyat</div>
                 </div>
            </li>
        </ul>
    </div>

    <div class="uk-navbar-right">
        <ul class="uk-navbar-nav uk-text-capitalize">           
            <li>&copy; 2018 ResumeGenius.com </a></li>
        </ul>
    </div>
</nav>
<br>

app/views/users/review.html.erb
<hr>
<div class="uk-container uk-flex uk-padding uk-background-muted">
         <div class="uk-container-primary uk-padding ">
               <h1 class="uk-heading-line" ><span>YOU'RE AWESOME<strong style="color: #f0506e;">!</strong></span></h1>
               <!-- <el style = "color: #f0506e;">FOLLOW 3 EASY STEPS</el>   -->
              <h3 class="uk-heading-line uk-text-left"><span>1. YOUR <strong style="color: #f0506e;">N</strong>AME</span></h3>

              <h3 class="uk-heading-line uk-text-center"><span>2. YOUR <strong style="color: #f0506e;">E</strong>MAIL ID</span></h3>

              <h3 class="uk-heading-line uk-text-right"><span>3. YOUR <strong style="color: #f0506e;">R</strong>EVIEW</h3>
              <br><br>
              THANKS FOR DOING THIS<strong style = "color: #f0506e;">!</strong> <BR>
              <strong style="color: #f0506e;">Z</strong>akwan <strong style="color: #f0506e;">B</strong>haiyat.
        </div>
      

        <div class="uk-container-primary uk-padding uk-align-center">
        	<legend class="uk-legend">Review</legend>
        	<hr>
			<form method="POST" action="https://formspree.io/zakwanbhaiyat23@gmail.com" target="_blank">
				
			  <div class="uk-margin">
            		<input class="uk-input" type="text" name="name" placeholder="Your Name">
       	 	  </div>
				
			  <div class="uk-margin">
            		<input class="uk-input" type="email" name="email" placeholder="Your Email-Id">
       	 	  </div>
			  <div class="uk-margin">
			  		
            		<textarea class="uk-textarea" rows="5" name="message" placeholder="Your Review message"></textarea>
        	  </div>
			  <br>
			  <button type="submit" class="uk-button uk-button-danger">Send</button>
			</form>
	</div>
</div>
<br><br>

app/views/users/show.html.erb
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/uikit/3.0.0-beta.38/css/uikit.min.css" />


<%= render partial: "shared/introduction", locals: {intro: @user_resume_introductions} %>

<%= render partial: "shared/objective", locals: {obj: @user_resume_objective} %>

<%= render partial: "shared/reskills", locals: {skill: @user_resume_reskills} %>

<%= render partial: "shared/experiances", locals: {exp: @user_resume_experiences} %>

<%= render partial: "shared/otherprojects", locals: {other: @user_resume_otherprojects} %>

<%= render partial: "shared/education", locals: {edu: @user_resume_education} %>

<%= render partial: "shared/subsection", locals: {sub: @user_resume_subsections} %>

<br><br><br>

app/views/users/show.pdf.erb
hello

app/views/users/viewresume.html.erb
<div class="uk-child-width-1-2@m uk-grid-small uk-grid-match" uk-grid style="line-height: 1;">
	<% if @user_resume_introductions && @user_resume_objective != nil %>
		<div class="uk-animation-toggle">
			<a class="uk-button uk-button-primary myButton" <%= link_to 'Template 1', user_path(:id => @current_user.id) %> </a>
		</div><br>
		<% else %>
		<strong style="color: #1e87f0;">Note</strong> :- Fill out <strong style="color: #f0506e;">B</strong>asic<strong style="color: #f0506e;">I</strong>nfo and <strong style="color: #f0506e;">S</strong>ummary section to <strong style="color: #f0506e;">V</strong>iew your <strong style="color: #f0506e;">R</strong>esume.<br>
	<% end %>
	<% if @user_resume_introductions && @user_resume_objective && @user_resume_reskills.length && @user_resume_experiences.length && @user_resume_otherprojects.length && @user_resume_education.length != 0 %>
		
		<div class="uk-animation-toggle">
 			<a class="uk-button uk-button-primary myButton" <%= link_to "Download Resume", users_path(:id => @current_user.id, format: 'pdf') %></a>
		</div>
		<% else %>
		<strong style="color: #1e87f0;">Note</strong> :- Fill out <strong style="color: #f0506e;">All</strong> the sections for <strong style="color: #f0506e;">D</strong>ownload your <strong style="color: #f0506e;">R</strong>esume.
	<% end %>

<br><br>

	<% if @user_resume_introductions && @user_resume_objective != nil %>
		<div class="uk-animation-toggle">
			<a class="uk-button uk-button-primary myButton" <%= link_to 'Template 2', newtemplate_path(:id => @current_user.id) %> </a>
		</div><br>
	<% end %>
	<% if @user_resume_introductions && @user_resume_objective && @user_resume_reskills.length && @user_resume_experiences.length && @user_resume_otherprojects.length && @user_resume_education.length != 0 %>
		
		<div class="uk-animation-toggle">
 			<a class="uk-button uk-button-primary myButton" <%= link_to "Download Resume", newtemplate_path(:id => @current_user.id, format: 'pdf') %></a>
		</div>
	<% end %>
</div>