config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'users#index'


  get "review", to: "users#review"
  get "newtemplate", to: "users#newtemplate"

  resources :resumes
  resources :introductions
  resources :objectives
  resources :summary
  resources :skills
  resources :experiences
  resources :projects
  resources :otherprojects
  resources :educations
  resources :reskills
  resources :sections do
    resources :subsections, only: [:new, :create]
  end
  resources :subsections, only:[:index, :edit, :update, :destroy]
  resources :users
end

app/models/education.rb
class Education < ApplicationRecord
	belongs_to :resume
end

app/models/experience.rb
class Experience < ApplicationRecord
	belongs_to :resume
	has_many :projects
end

app/models/introduction.rb
class Introduction < ApplicationRecord
	belongs_to :resume
end

app/models/objective.rb
class Objective < ApplicationRecord

	belongs_to :resume
end

app/models/otherproject.rb
class Otherproject < ApplicationRecord
	belongs_to :resume
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :experiences
	belongs_to :resume
end

app/models/reskill.rb
class Reskill < ApplicationRecord
	belongs_to :resume
	belongs_to :skill
end

app/models/resume.rb
class Resume < ApplicationRecord
	has_one :introduction
	has_one :summary
	has_one :objective
	has_many :reskills
	has_many :skills, :through => :reskills
	has_many :projects
	has_many :otherprojects
	has_many :educations
	has_many :experiences
	has_many :sections
	has_many :subsections, :through => :sections
	belongs_to :user
end

app/models/section.rb
class Section < ApplicationRecord
	has_many :subsections
	belongs_to :resume
end

app/models/skill.rb
class Skill < ApplicationRecord
	has_many :reskills
	has_many :resume, :through => :reskills
end

app/models/subsection.rb
class Subsection < ApplicationRecord
	belongs_to :section
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :resume
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/reskills_helper.rb
module ReskillsHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/shared/_education.html.erb
<div class="uk-container">
  <% if @user_resume_education.length != 0 %>
    <h3 class="uk-article-title" style="font-size: 16px; margin-bottom: 10px;"><b>EDUCATION</b> </h3>
    

         <% @user_resume_education.each do |t| %>

            <span style="margin-top: 10px; margin-bottom: 5px; font-size: 12px;"> <%= t.name %> </span>

              <div class="uk-child-width-1-2@m uk-child-width-1-2@s" uk-grid style="line-height: 0;">
                  <div style="line-height: 1;">
                      <span class="uk-text-left" style="font-size: 12px; color: black;"><%= t.degree %></span>
                  </div>
                  <div class="uk-text-right">
                      <span style=" font-size: 12px; color:black;"><%= t.year_graduated %></span>
                  </div>
              </div>
        <% end %>
  <% end %>
</div>

app/views/shared/_experiances.html.erb
  <div class="uk-container" style="margin-bottom: 10px;">
    <% if @user_resume_experiences.length != 0 %>
      <h3 class="uk-article-title" style="font-size: 16px; margin-bottom: 5px;"><b>WORK HISTORY </b></h3>
      
           <% @user_resume_experiences.each do |t| %>
                       
                <span class="uk-text-left;" style="font-size: 12px;">
                    <%= t.job_title %>
                </span>

                <div class="uk-child-width-1-2@m uk-child-width-1-2@s" uk-grid style="line-height: 0;">
                  <div style="line-height: 0.5;">
                      <span class="uk-text-left" style="font-size: 12px; color: black;"><%= t.company %></span>
                  </div>
                  <div class="uk-text-right" style="line-height: 0.5;">
                      <span style=" font-size: 12px; color:black;"><%= t.startdate %>-<%= t.enddate %></span>
                  </div>
                </div>

                <p class="uk-text-small" style="margin-top: 5px; margin-bottom: 5px; color: black; font-size: 12px;"><%= t.description %></p>
          <% end %>
  </div> 
<% end %>

         

app/views/shared/_introduction.html.erb
<div class="uk-container uk-panel">
  <div class="uk-card " style="padding-bottom: 10px;">
    <h1 class="uk-card-title uk-text-center" style=" margin-bottom: 0px; font-size: 26px;">
      <strong><%= intro.name %></strong>
    </h1>
    <h4 class="uk-text-center" style="margin-top: 0px; margin-bottom: 2px;" >
      <%= intro.title %>
    </h4>
    
        <div class="uk-text-center uk-h6 " style="margin-top: 0px; margin-bottom: 0px;">
          <!-- <span uk-icon="icon: info"></span> -->
          <span><%= intro.address %></span>  |  
          <span>(C) <%= intro.phone %></span>  |  
          <span><%= intro.email %></span>
        </div>

        <div class="uk-text-center uk-h6" style="margin-top: 5px; margin-bottom: 5px;"">
           <% unless intro.linkdin.blank? %>
              <span style="margin-right: 40px;">
                 <a href = <%= intro.linkdin %> target = "_blank"> linkdin/<%= intro.name %> </a>
              </span>
            <% end %>
            <% unless intro.portfolio.blank? %>
              <span style="margin-left: 50px;">
                <a href = <%= intro.portfolio %> target = "_blank"> My-Portfolio</a>
              </span>
            <% end %>
            <% unless intro.github.blank? %>
              <span style="margin-left: 90px;">
                <a href = <%= intro.github %> target = "_blank"> Github/<%= intro.name %></a>
              </span>
            <% end %>
        </div>

       

<b><hr style="color: black; margin-bottom: 10px;"></b>

<!-- <div class="uk-child-width-1-3@m uk-child-width-1-2@s" uk-grid >
        <div class="uk-text-left uk-h5">
          <span uk-icon="icon: info"></span>
          <span><%= intro.address %></span>
        </div>
        <div class="uk-text-center uk-h5">
          <span uk-icon="icon: phone"></span>
          <span><%= intro.phone %></span>
        </div>
        <div class="uk-text-right uk-h5">
          <span uk-icon="icon: mail"></span>
          <span><%= intro.email %></span>
        </div>
</div>    -->

app/views/shared/_layout2.html.erb
<div class="uk-container uk-panel">
  <div class="uk-card uk-card-body">
    <h3 class="uk-card-title uk-text-center" style="line-height: 0;">
      <%= intro.name %>
    </h3>
    <h4 class="uk-text-center" style="color:red; line-height: 0;margin-top: 30px;">
      <%= intro.title %>
    </h4>
    <div class="uk-child-width-1-3@m uk-child-width-1-2@s" uk-grid >
        <div class="uk-text-left uk-h5">
          <span uk-icon="icon: info"></span>
          <span><%= intro.address %></span>
        </div>
        <div class="uk-text-center uk-h5">
          <span uk-icon="icon: phone"></span>
          <span><%= intro.phone %></span>
        </div>
        <div class="uk-text-right uk-h5">
          <span uk-icon="icon: mail"></span>
          <span><%= intro.email %></span>
        </div>
    </div>   
</div>

app/views/shared/_objective.html.erb
<div class="uk-container" style="margin-bottom: 10px;">
	<article class="uk-article">

	<% if @user_resume_introductions != nil %>
    	<h1 class="uk-article-title" style="font-size: 16px;margin-bottom:0px;"><b>PROFESSIONAL SUMMARY</b></h1>
			<p class="uk-article-meta" style="color: black; font-size: 12px; margin-top: 10px;"><%= obj.description %></p>
	<% end %>
</article>  
</div>

app/views/shared/_otherprojects.html.erb
<div class="uk-container" style="margin-bottom: 10px;">
	<% if @user_resume_otherprojects.length != 0 %>
		<article class="uk-article">
	    	<h1 class="uk-article-title" style="font-size: 16px;margin-bottom:10px;"><b>PROJECTS</b></h1>
			<% @user_resume_otherprojects.each do |t| %>
				<strong style="font-size: 14px; margin-top: 0px;"><%= t.name %></strong>
				<ul class="uk-list uk-list-none" style="margin-top: 0px; margin-bottom: 4px; font-size: 12px; color: black; list-style: none;">
				    <li style="margin-top: 2px;"> - <%= t.desc1 %></li>
				    <li style="margin-top: 2px;"> - <%= t.desc2 %></li>
				    <% unless t.desc3.blank? %>
				    	<li style="margin-top: 2px;"> - <%= t.desc3 %></li>
				    <% end %>
				    <% unless t.desc4.blank? %>
				    	<li style="margin-top: 2px;"> - <%= t.desc4 %></li>
				 	<% end %>
				    
				</ul>
			<% end %>
		</article>
	<% end %>  
</div>

app/views/shared/_projects.html.erb
    
<div class="uk-overflow-auto">

    <table class="uk-table">
    <h1 class="uk-article-title" style="font-size: 24px;margin-bottom: 10px;"><b> Projects </b> </h1>
    
    <tbody >
        <tr>
            <% @user_resume_projects.each do |t| %>
            <td><%= @experience.find(t.experience_id).company %></td>
            <td><%= t.name %></td>
            <td><%= t.description %></td>
            <% end %>
        </tr>
    </tbody>
    
</table>
</div>

app/views/shared/_reskills.html.erb
<div class="uk-overflow-auto" style="margin-bottom: 10px;">

    <% if @user_resume_reskills.length != 0 %>
        <h1 class="uk-article-title" style="font-size: 16px;margin-bottom: 5px;"> <b>SKILLS</b> </h1>
        <table class="uk-table" style="margin-top: 0px;line-height: 0px;;">
            <tbody >
                <% next_end = 3 %>
                <% skill.each_with_index do |t, i| %>
                    <% if i % 4 == 0 %>
                        <tr>
                    <% end %>  
                 
                    <% Skill.where("id = '#{t.skill_id}'").each do |x| %>
                        <td style="font-size: 12px; padding-bottom: 8px; color: black;"><%= x.name %></td>
                    <% end %>



                    <% if next_end  == i %>
                        <% next_end = next_end + 4 %>
                        </tr>
                    <% end %> 
                     

                 <% end %>
             </tr>
         </tbody>
        </table>
    <% end %>
</div>

app/views/shared/_skills.html.erb
    
<div class="uk-overflow-auto" style="margin-bottom: 10px;">

    
    <h1 class="uk-article-title" style="font-size: 24px;margin-bottom: 5px;"> <b>SKILLS</b> </h1>
    
    <table class="uk-table" style="margin-top: 0px;line-height: 0px;;">
    <tbody >
        <tr>
            <% @user_resume_skills.each do |t| %>
            <td><%= t.name %>
        <a <%= link_to "Edit", edit_skill_path(t) %></a>|
        <a  <%= link_to "Remove", skill_path(t), method: :delete, data: { confirm: "Are you sure?" } %></a>
    </div>
            </td>


            <% end %>

        </tr>
    </tbody>
    
</table>
</div>

app/views/shared/_subsection.html.erb
<br>

<div class="uk-container" style="margin-bottom: 10px;">
	<% if @user_resume_subsections.length != 0 %>
		<% @user_resume_sections.each do |section| %>
			<article class="uk-article">
		    	<h1 class="uk-article-title uk-text-uppercase" style="font-size: 16px;margin-bottom:10px;"><b><%= section.name %> </b></h1>
					<% section.subsections.each do |subsection| %>
						<span style="font-size: 12px; margin-top: 0px; color: black;">
							<%= subsection.name %>
						</span>
						<ul class="uk-list uk-list-none" style="margin-top: 0px; margin-bottom: 4px; font-size: 12px; color: black; list-style: none;">
							<% unless subsection.desc1.blank? %>
						    	<li style="margin-top: 2px;"> - <%= subsection.desc1 %></li>
						    <% end %>
						    <% unless subsection.desc2.blank? %>
						    	<li style="margin-top: 2px;"> - <%= subsection.desc2 %></li>
						    <% end %>
						    <% unless subsection.desc3.blank? %>
						    	<li style="margin-top: 2px;"> - <%= subsection.desc3 %></li>
						    <% end %>
						    <% unless subsection.desc4.blank? %>
						    	<li style="margin-top: 2px;"> - <%= subsection.desc4 %></li>
						 	<% end %>
						</ul>
						<div class="uk-text-right" style="line-height: 0.0;">
                      		<span style=" font-size: 12px; color:black;">
                      			<%= subsection.date %>
                      		</span>
                  		</div>
					<% end %>
				<% end %>
			</article>
	<% end %>  
</div>