config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :controllers => { :registrations => 'users/registrations' }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  root to: 'users#index'


  get "review", to: "users#review"
  get "newtemplate", to: "users#newtemplate"

  resources :resumes
  resources :introductions
  resources :objectives
  resources :summary
  resources :skills
  resources :experiences
  resources :projects
  resources :otherprojects
  resources :educations
  resources :reskills
  resources :sections do
    resources :subsections, only: [:new, :create]
  end
  resources :subsections, only:[:index, :edit, :update, :destroy]
  resources :users
end

app/models/education.rb
class Education < ApplicationRecord
	belongs_to :resume
end

app/models/experience.rb
class Experience < ApplicationRecord
	belongs_to :resume
	has_many :projects
end

app/models/introduction.rb
class Introduction < ApplicationRecord
	belongs_to :resume
end

app/models/objective.rb
class Objective < ApplicationRecord

	belongs_to :resume
end

app/models/otherproject.rb
class Otherproject < ApplicationRecord
	belongs_to :resume
end

app/models/project.rb
class Project < ApplicationRecord
	belongs_to :experiences
	belongs_to :resume
end

app/models/reskill.rb
class Reskill < ApplicationRecord
	belongs_to :resume
	belongs_to :skill
end

app/models/resume.rb
class Resume < ApplicationRecord
	has_one :introduction
	has_one :summary
	has_one :objective
	has_many :reskills
	has_many :skills, :through => :reskills
	has_many :projects
	has_many :otherprojects
	has_many :educations
	has_many :experiences
	has_many :sections
	has_many :subsections, :through => :sections
	belongs_to :user
end

app/models/section.rb
class Section < ApplicationRecord
	has_many :subsections
	belongs_to :resume
end

app/models/skill.rb
class Skill < ApplicationRecord
	has_many :reskills
	has_many :resume, :through => :reskills
end

app/models/subsection.rb
class Subsection < ApplicationRecord
	belongs_to :section
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_one :resume
end

app/controllers/educations_controller.rb
class EducationsController < ApplicationController
	def index
		@user_resume_education = User.find(current_user.id).resume.educations
	end

	def show
		@user_resume_education = User.find(current_user.id).resume.educations
	end


	def new
		@user_resume = User.find(current_user.id).resume.id
		@education = Education.new(params[:resume_id])
	end

	def create
		@education = Education.create(resume_id: params[:education][:resume_id],name: params[:education][:name],degree: params[:education][:degree],year_graduated: params[:education][:year_graduated])
		if @education.save
			redirect_to users_path
			flash[:notice] = "Education Created"
		else
			render 'education/new'
		end
    end
	
	def edit
		@user_resume_education = Education.find(params[:id])
	end

	def update
		@user_resume_education = Education.find(params[:id])
		@user_resume_education.update_attributes(education_params)
		redirect_to users_path
	end

	def destroy
		@user_resume_education = Education.find(params[:id])
		@user_resume_education.delete
		redirect_to users_path
	end

	private

	def set_education
    	@education = Education.find_by(resume: params[:id])
  	end

  	def set_resume
    	@resume = Resume.find_by(user: params[:resume_id])
  	end
  	def education_params 
  		params.require(:education).permit(:name,:degree,:year_graduated)
  	end
end

app/helpers/education_helper.rb
module EducationHelper
end

app/helpers/educations_helper.rb
module EducationsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/helpers/reskills_helper.rb
module ReskillsHelper
end

app/helpers/resume_helper.rb
module ResumeHelper
end

app/helpers/resumes_helper.rb
module ResumesHelper
end

app/helpers/sections_helper.rb
module SectionsHelper
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/summary_helper.rb
module SummaryHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/educations/edit.html.erb
<div class= "uk-container uk-background-muted uk-padding uk-panel" style="padding: 50px;margin-top: 150px;">
    <h2> Edit your Education here </h2><br>
        <%= form_for @user_resume_education do |f| %>

            <%= f.hidden_field :resume_id, :value => @user_resume %>

            College Name
            <div class="uk-form-controls">
                <input class="uk-input" type="text" placeholder="Name of the college"
                <%= f.text_field :name, :required => true %>
            </div>
            
            Degree Name
            <div class="uk-form-controls">
                <input class="uk-input" type="text" placeholder="ex. Bachelor of Technology (B.Tech.)"
                <%= f.text_field :degree, :required => true %>
            </div>

            Graduation Year (ex. Feb,2018)
            <div class="uk-form-controls">
                <input class="uk-input" type="text" placeholder="ex. Feb,2018"
                <%= f.text_field :year_graduated, :required => true %>
            </div>

             
             <br>
            <button class="uk-button uk-button-primary"
                 <%= submit_tag "Add" %> UPDATE
             </button>
    
        <% end %>
        
</div>

app/views/educations/index.html.erb
<div class="uk-container">
    <h3 class="uk-article-title" style="font-size: 24px; margin-bottom: 10px;"><b>EDUCATION</b> </h3>
    

         <% @user_resume_education.each do |t| %>

            <h5 style="margin-top: 10px; margin-bottom: 5px;"> <%= t.name %> </h5>

              <div class="uk-child-width-1-2@m uk-child-width-1-2@s" uk-grid style="line-height: 0;">
                  <div style="line-height: 1;">
                      <span class="uk-text-left"><%= t.degree %></span>
                  </div>
                  <div>
                      <span class="uk-text-right" style="margin-left: 445px;"><%= t.year_graduated %></span>
                  </div>
              </div>
              <a <%= link_to "Edit", edit_education_path(t) %></a> 

      | 
             <a <%= link_to "Remove", education_path(t), method: :delete, data: { confirm: "Are you sure?" } %></a> |
        <% end %>
</div>

app/views/educations/new.html.erb
<div class= "uk-container uk-background-muted uk-padding uk-panel" style="padding: 50px;margin-top: 150px;">
    <h2> Add your Education here </h2><br>
        <%= form_for @education do |f| %>

            <%= f.hidden_field :resume_id, :value => @user_resume %>

            College Name
            <div class="uk-form-controls">
                <input class="uk-input" type="text" placeholder="Name of the college"
                <%= f.text_field :name, :required => true %>
            </div>
            
            Degree Name
            <div class="uk-form-controls">
                <input class="uk-input" type="text" placeholder="ex. Bachelor of Technology (B.Tech.)"
                <%= f.text_field :degree, :required => true %>
            </div>

            Graduation Year (ex. Feb,2018)
            <div class="uk-form-controls">
                <input class="uk-input" type="text" placeholder="ex. Feb,2018"
                <%= f.text_field :year_graduated, :required => true %>
            </div>

             
             <br>
            <button class="uk-button uk-button-primary"
                 <%= submit_tag "Add" %> ADD
             </button>
        <% end %>
        
</div>